theme = "onedark"

[editor]
line-number = "relative"
mouse = true
auto-save  = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":w"   

[editor.statusline]
left = ["mode", "spinner", "version-control","register",]
center = ["file-name"]
right = ["diagnostics", "selections", "position","total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "V"

