notARepository: "quit"
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - cyan
      - bold
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - black
      - bold
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: "3"
